source "https://rubygems.org"

gem 'rspec', '3.9.0'
gem 'capybara', '3.29.0'
gem 'capybara-screenshot'
gem 'cucumber', '3.1.2'
gem 'selenium-webdriver', '3.142.6'
gem 'childprocess', '3.0.0'
gem 'report_builder'
gem 'ffi'
gem 'faker'
gem 'cpf_faker'